
AstaKit:
  FriWahl:
    BallotBoxBackend:
      votingLogger:
        logger: TYPO3\Flow\Log\Logger
        backend: TYPO3\Flow\Log\Backend\FileBackend
        backendOptions:
          logFileURL: %FLOW_PATH_DATA%Logs/Voting.log
          createParentDirectories: TRUE
          severityThreshold: %LOG_INFO%
          maximumLogFileSize: 10485760
          logFilesToKeep: 10
          logMessageOrigin: FALSE
