FROM        php:5.6-fpm-alpine
MAINTAINER  Andrej Rode <andrej.rode@asta-kit.de>

ENV         security_updates_as_of 2017_06_01

RUN         set -ex; \
            \
            docker-php-ext-install pdo_mysql
