FROM        php:5.6-fpm-alpine
MAINTAINER  Andrej Rode <andrej.rode@asta-kit.de>

ENV         security_updates_as_of 2021_04_21

RUN         set -ex; \
            \
            docker-php-ext-install pdo_mysql
RUN         apk add git
RUN         curl -s https://getcomposer.org/download/1.5.6/composer.phar -o /bin/composer
