<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7bc949c8b83bf04da6fadc8374d521bd
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Component\\Debug\\' => 24,
            'Symfony\\Component\\Console\\' => 26,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Component\\Debug\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/debug',
        ),
        'Symfony\\Component\\Console\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/console',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static $prefixesPsr0 = array (
        'o' => 
        array (
            'org\\bovigo\\vfs\\' => 
            array (
                0 => __DIR__ . '/..' . '/mikey179/vfsStream/src/main/php',
            ),
        ),
        'T' => 
        array (
            'TYPO3\\Welcome' => 
            array (
                0 => __DIR__ . '/../../..' . '/Packages/Framework/TYPO3.Welcome/Classes',
            ),
            'TYPO3\\Party' => 
            array (
                0 => __DIR__ . '/../../..' . '/Packages/Framework/TYPO3.Party/Classes',
            ),
            'TYPO3\\Kickstart' => 
            array (
                0 => __DIR__ . '/../../..' . '/Packages/Framework/TYPO3.Kickstart/Classes',
            ),
            'TYPO3\\Fluid' => 
            array (
                0 => __DIR__ . '/../../..' . '/Packages/Framework/TYPO3.Fluid/Classes',
            ),
            'TYPO3\\Flow' => 
            array (
                0 => __DIR__ . '/../../..' . '/Packages/Framework/TYPO3.Flow/Classes',
            ),
            'TYPO3\\Eel' => 
            array (
                0 => __DIR__ . '/../../..' . '/Packages/Framework/TYPO3.Eel/Classes',
            ),
        ),
        'S' => 
        array (
            'Symfony\\Component\\Yaml' => 
            array (
                0 => __DIR__ . '/..' . '/symfony/yaml',
            ),
            'Symfony\\Component\\DomCrawler\\' => 
            array (
                0 => __DIR__ . '/..' . '/symfony/dom-crawler',
            ),
        ),
        'D' => 
        array (
            'Doctrine\\ORM' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/orm/lib',
            ),
            'Doctrine\\DBAL\\Migrations' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/migrations/lib',
            ),
            'Doctrine\\DBAL' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/dbal/lib',
            ),
            'Doctrine\\Common\\Lexer\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/lexer/lib',
            ),
            'Doctrine\\Common\\Inflector\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/inflector/lib',
            ),
            'Doctrine\\Common\\Collections\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/collections/lib',
            ),
            'Doctrine\\Common\\Cache\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/cache/lib',
            ),
            'Doctrine\\Common\\Annotations\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/annotations/lib',
            ),
            'Doctrine\\Common\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/common/lib',
            ),
        ),
        'A' => 
        array (
            'AstaKit\\FriWahl\\VoterDirectory' => 
            array (
                0 => __DIR__ . '/../../..' . '/Packages/Application/AstaKit.FriWahl.VoterDirectory/Classes',
            ),
            'AstaKit\\FriWahl\\Core' => 
            array (
                0 => __DIR__ . '/../../..' . '/Packages/Application/AstaKit.FriWahl.Core/Classes',
            ),
            'AstaKit\\FriWahl\\BallotBoxBackend' => 
            array (
                0 => __DIR__ . '/../../..' . '/Packages/Application/AstaKit.FriWahl.BallotBoxBackend/Classes',
            ),
            'AstaKit\\FriWahl\\AdminInterface' => 
            array (
                0 => __DIR__ . '/../../..' . '/Packages/Application/AstaKit.FriWahl.AdminInterface/Classes',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7bc949c8b83bf04da6fadc8374d521bd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7bc949c8b83bf04da6fadc8374d521bd::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit7bc949c8b83bf04da6fadc8374d521bd::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
