<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Migration to add the identifier column to BallotBox
 */
class Version20140704131814 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_vote DROP FOREIGN KEY FK_4151BA22B32AB266");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_ballotbox DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_ballotbox CHANGE persistence_object_identifier identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_ballotbox ADD PRIMARY KEY (identifier)");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_vote ADD CONSTRAINT FK_4151BA22B32AB266 FOREIGN KEY (ballotbox) REFERENCES astakit_friwahl_core_domain_model_ballotbox (identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_vote DROP FOREIGN KEY FK_4151BA22B32AB266");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_ballotbox DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_ballotbox CHANGE identifier persistence_object_identifier VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_ballotbox ADD PRIMARY KEY (persistence_object_identifier)");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_vote ADD CONSTRAINT FK_4151BA22B32AB266 FOREIGN KEY (ballotbox) REFERENCES astakit_friwahl_core_domain_model_ballotbox (persistence_object_identifier)");
	}

}