<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Migration to change the identity field of Election to an internal identifier instead of the autogenerated
 * persistence_object_identifier.
 */
class Version20140531123256 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		// Drop all (foreign) keys pointing to the election identifier
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_ballotbox DROP FOREIGN KEY FK_14BFDB15DCA03800");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_electionperiod DROP FOREIGN KEY FK_7FD34A7BDCA03800");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_eligiblevoter DROP FOREIGN KEY FK_C5D59B3EDCA03800");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_voting DROP FOREIGN KEY FK_EC6D04AADCA03800");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_election DROP PRIMARY KEY");

		// rename the election identifier
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_election CHANGE persistence_object_identifier identifier VARCHAR(40) NOT NULL");

		// re-add constraints and foreign keys
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_election ADD PRIMARY KEY (identifier)");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_ballotbox ADD CONSTRAINT FK_14BFDB15DCA03800 FOREIGN KEY (election) REFERENCES astakit_friwahl_core_domain_model_election (identifier)");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_electionperiod ADD CONSTRAINT FK_7FD34A7BDCA03800 FOREIGN KEY (election) REFERENCES astakit_friwahl_core_domain_model_election (identifier)");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_eligiblevoter ADD CONSTRAINT FK_C5D59B3EDCA03800 FOREIGN KEY (election) REFERENCES astakit_friwahl_core_domain_model_election (identifier)");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_voting ADD CONSTRAINT FK_EC6D04AADCA03800 FOREIGN KEY (election) REFERENCES astakit_friwahl_core_domain_model_election (identifier)");

		// additionally make election names unique
		$this->addSql("CREATE UNIQUE INDEX UNIQ_2EEF2AE45E237E06 ON astakit_friwahl_core_domain_model_election (name)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		// Drop all (foreign) keys pointing to the election identifier
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_ballotbox DROP FOREIGN KEY FK_14BFDB15DCA03800");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_electionperiod DROP FOREIGN KEY FK_7FD34A7BDCA03800");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_eligiblevoter DROP FOREIGN KEY FK_C5D59B3EDCA03800");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_voting DROP FOREIGN KEY FK_EC6D04AADCA03800");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_election DROP PRIMARY KEY");

		// rename the election identifier
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_election CHANGE identifier persistence_object_identifier VARCHAR(40) NOT NULL");

		// re-add constraints and foreign keys
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_election ADD PRIMARY KEY (persistence_object_identifier)");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_ballotbox ADD CONSTRAINT FK_14BFDB15DCA03800 FOREIGN KEY (election) REFERENCES astakit_friwahl_core_domain_model_election (persistence_object_identifier)");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_electionperiod ADD CONSTRAINT FK_7FD34A7BDCA03800 FOREIGN KEY (election) REFERENCES astakit_friwahl_core_domain_model_election (persistence_object_identifier)");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_eligiblevoter ADD CONSTRAINT FK_C5D59B3EDCA03800 FOREIGN KEY (election) REFERENCES astakit_friwahl_core_domain_model_election (persistence_object_identifier)");
		$this->addSql("ALTER TABLE astakit_friwahl_core_domain_model_voting ADD CONSTRAINT FK_EC6D04AADCA03800 FOREIGN KEY (election) REFERENCES astakit_friwahl_core_domain_model_election (persistence_object_identifier)");

		// remove unique constraint for election name
		$this->addSql("DROP INDEX UNIQ_2EEF2AE45E237E06 ON astakit_friwahl_core_domain_model_election");
	}
}